import type { Campaign } from "@/lib/types";
import { toMinorUnits } from "@/lib/utils/currency";

export const campaigns: Campaign[] = [
  {
    id: "camp-maternal-health",
    organizationId: "org-horizon",
    slug: "maternal-health-program",
    title: "Maternal Health Program",
    description:
      "Prenatal checkups, safe delivery support and postnatal care for mothers across rural Kenya, delivered through community clinics and mobile health teams.",
    imageUrl: "",
    category: "health",
    location: "Kenya",
    currency: "USD",
    fundingGoal: toMinorUnits(150000),
    amountRaised: toMinorUnits(128400),
    amountUtilized: toMinorUnits(94200),
    startDate: "2025-09-01T00:00:00Z",
    status: "active",
    updates: [
      {
        id: "upd-mh-1",
        campaignId: "camp-maternal-health",
        title: "Two new mobile clinics reached remote villages this month",
        body: "Our mobile health teams completed 340 prenatal checkups and 28 safe deliveries across four villages that previously had no nearby clinic access.",
        postedAt: "2026-08-02T00:00:00Z",
      },
    ],
  },
  {
    id: "camp-childrens-nutrition",
    organizationId: "org-horizon",
    slug: "childrens-nutrition-program",
    title: "Children's Nutrition Program",
    description:
      "Therapeutic and supplementary feeding for children under five showing signs of malnutrition, paired with caregiver nutrition education.",
    imageUrl: "",
    category: "food_security",
    location: "Kenya",
    currency: "USD",
    fundingGoal: toMinorUnits(90000),
    amountRaised: toMinorUnits(64200),
    amountUtilized: toMinorUnits(38900),
    startDate: "2025-11-15T00:00:00Z",
    status: "active",
    updates: [],
  },
  {
    id: "camp-school-support",
    organizationId: "org-brightpath",
    slug: "school-support-program",
    title: "School Support Program",
    description:
      "Classroom construction, textbooks and teacher stipends for under-resourced primary schools across Punjab and Sindh.",
    imageUrl: "",
    category: "education",
    location: "Pakistan",
    currency: "PKR",
    fundingGoal: toMinorUnits(15000000),
    amountRaised: toMinorUnits(9800000),
    amountUtilized: toMinorUnits(6120000),
    startDate: "2025-08-01T00:00:00Z",
    status: "active",
    updates: [
      {
        id: "upd-ss-1",
        campaignId: "camp-school-support",
        title: "Textbooks delivered to 6 partner schools",
        body: "New textbooks and supply kits reached over 1,100 students ahead of the new term.",
        postedAt: "2026-07-20T00:00:00Z",
      },
    ],
  },
  {
    id: "camp-girls-literacy",
    organizationId: "org-brightpath",
    slug: "girls-literacy-initiative",
    title: "Girls' Literacy Initiative",
    description:
      "After-school literacy circles and take-home reading materials designed to keep girls engaged in reading beyond the classroom.",
    imageUrl: "",
    category: "education",
    location: "Pakistan",
    currency: "PKR",
    fundingGoal: toMinorUnits(8000000),
    amountRaised: toMinorUnits(8000000),
    amountUtilized: toMinorUnits(5400000),
    startDate: "2025-03-01T00:00:00Z",
    endDate: "2026-03-01T00:00:00Z",
    status: "completed",
    updates: [],
  },
  {
    id: "camp-flood-relief",
    organizationId: "org-clearwater",
    slug: "emergency-flood-relief-bangladesh",
    title: "Emergency Flood Relief — Bangladesh",
    description:
      "Emergency shelter, clean water and food distribution for families displaced by seasonal flooding in southern Bangladesh.",
    imageUrl: "",
    category: "emergency_relief",
    location: "Bangladesh",
    currency: "GBP",
    fundingGoal: toMinorUnits(100000),
    amountRaised: toMinorUnits(41200),
    amountUtilized: toMinorUnits(0),
    startDate: "2026-07-05T00:00:00Z",
    status: "active",
    updates: [],
  },
  {
    id: "camp-typhoon-recovery",
    organizationId: "org-clearwater",
    slug: "typhoon-recovery-philippines",
    title: "Typhoon Recovery — Philippines",
    description:
      "Rebuilding support and livelihood recovery grants for coastal communities affected by seasonal typhoons.",
    imageUrl: "",
    category: "emergency_relief",
    location: "Philippines",
    currency: "GBP",
    fundingGoal: toMinorUnits(120000),
    amountRaised: toMinorUnits(76300),
    amountUtilized: toMinorUnits(0),
    startDate: "2026-05-20T00:00:00Z",
    status: "active",
    updates: [],
  },
  {
    id: "camp-winter-aid",
    organizationId: "org-alnoor",
    slug: "winter-aid-displaced-families",
    title: "Winter Aid for Displaced Families",
    description: "Seasonal essentials, heating support and food vouchers for families facing hardship across the UAE.",
    imageUrl: "",
    category: "poverty",
    location: "United Arab Emirates",
    currency: "AED",
    fundingGoal: toMinorUnits(300000),
    amountRaised: toMinorUnits(118000),
    amountUtilized: toMinorUnits(0),
    startDate: "2026-01-10T00:00:00Z",
    status: "active",
    updates: [],
  },
  {
    id: "camp-assistive-devices",
    organizationId: "org-alnoor",
    slug: "assistive-devices-program",
    title: "Assistive Devices Program",
    description: "Wheelchairs, hearing aids and mobility equipment provided at no cost to families who cannot afford them.",
    imageUrl: "",
    category: "disability",
    location: "United Arab Emirates",
    currency: "AED",
    fundingGoal: toMinorUnits(150000),
    amountRaised: toMinorUnits(22000),
    amountUtilized: toMinorUnits(0),
    startDate: "2026-04-01T00:00:00Z",
    status: "active",
    updates: [],
  },
  {
    id: "camp-cancer-treatment",
    organizationId: "org-maple",
    slug: "cancer-treatment-assistance",
    title: "Cancer Treatment Assistance",
    description:
      "Covers treatment gaps, travel and accommodation costs for families of children undergoing cancer treatment away from home.",
    imageUrl: "",
    category: "health",
    location: "Canada",
    currency: "CAD",
    fundingGoal: toMinorUnits(200000),
    amountRaised: toMinorUnits(142000),
    amountUtilized: toMinorUnits(97300),
    startDate: "2025-06-01T00:00:00Z",
    status: "active",
    updates: [
      {
        id: "upd-ct-1",
        campaignId: "camp-cancer-treatment",
        title: "12 families supported with travel costs this quarter",
        body: "Families traveling from rural Ontario and Manitoba received support covering transportation and short-term accommodation near treatment centers.",
        postedAt: "2026-08-15T00:00:00Z",
      },
    ],
  },
  {
    id: "camp-pediatric-nutrition",
    organizationId: "org-maple",
    slug: "pediatric-nutrition-support",
    title: "Pediatric Nutrition Support",
    description: "Specialized nutrition formula and dietitian support for children undergoing intensive medical treatment.",
    imageUrl: "",
    category: "children",
    location: "Canada",
    currency: "CAD",
    fundingGoal: toMinorUnits(60000),
    amountRaised: toMinorUnits(51500),
    amountUtilized: toMinorUnits(29800),
    startDate: "2025-10-01T00:00:00Z",
    status: "active",
    updates: [],
  },
];

export function getCampaignById(id: string): Campaign | undefined {
  return campaigns.find((c) => c.id === id);
}

export function getCampaignsByOrg(organizationId: string): Campaign[] {
  return campaigns.filter((c) => c.organizationId === organizationId);
}
